sonar.exclusions=**/package-lock.json,**/node_modules/**,**/dist/**,**/release/**,docs/**,fh6-relay/_python_archive/**,**/_python_archive/**

sonar.cpd.exclusions=**/package-lock.json,docs/**,fh6-relay/_python_archive/**,**/_python_archive/**
