apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fh6-timeattack-bot-data
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.data.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fh6-timeattack-bot-screenshots
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.screenshots.size }}
