apiVersion: v1
kind: Secret
metadata:
  name: fh6-timeattack-bot-secret
type: Opaque
stringData:
  DISCORD_TOKEN: {{ .Values.discord.token | quote }}
  DISCORD_GUILD_ID: {{ .Values.discord.guildId | quote }}
