image:
  repository: fh6-timeattack-bot
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

discord:
  token: ""
  guildId: ""

storage:
  storageClass: ""
  data:
    size: 1Gi
  screenshots:
    size: 5Gi
